=== JaneliaSciComp/figleaf/figleaf/figshare/create_article_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "is_metadata_record": {
      "type": "boolean"
    },
    "metadata_reason": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "references": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^http://"
      }
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "categories_by_source_id": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "orcid_id": {
            "type": "string"
          }
        }
      }
    },
    "custom_fields": {
      "type": "object"
    },
    "defined_type": {
      "type": "string",
      "enum": ["figure", "online resource", "preprint", "book", "conference contribution", "media", "dataset", "poster", "journal contribution", "presentation", "thesis", "software"]
    },
    "funding": {
      "type": "string"
    },
    "group_id": {
      "type": "integer"
    }
  },
  "required": ["title"]
}

=== JaneliaSciComp/figleaf/figleaf/figshare/metadata2.json
{
    "title": "My cool dataset",
    "description": "While counting numbers is quite common, little is known about the true meaning of numbers. In this study, a series of random numbers was generated. Surprisingly, we found no evidence that numbers alone are inherently meaningful. This study suggests that numbers are not sufficient to explain their own meaning.",
    "is_metadata_record": true,
    "metadata_reason": "Data file to be uploaded separately via API",
    "tags": [
        "Single neuron reconstruction"
    ],
    "keywords": [
        "Single neuron reconstruction"
    ],
    "categories": [
        25718,
        26104
    ],
    "categories_by_source_id": [
        "310112",
        "320999"
    ],
    "authors": [
        {
            "id": 2933718,
            "name": "Virginia Scarlett"
        },
        {
            "name": "Ana Van Gulick"
        },
        {
            "name": "William Shakespeare",
            "first_name": "William",
            "last_name": "Shakespeare",
            "email": "thebard@hotmail.com",
            "orcid_id": "000-000-12345"
        }
    ],
    "defined_type": "dataset"
}

=== JaneliaSciComp/figleaf/figleaf/figshare/researcher_metadata.json
{
    "title": "My cool dataset",
    "description": "While counting numbers is quite common, little is known about the true meaning of numbers. In this study, a series of random numbers was generated. Surprisingly, we found no evidence that numbers alone are inherently meaningful. This study suggests that numbers are not sufficient to explain their own meaning.",
    "is_metadata_record": true,
    "metadata_reason": "Data file to be uploaded separately via API",
    "tags": [
        "Single neuron reconstruction"
    ],
    "keywords": [
        "Single neuron reconstruction"
    ],
    "references": [],
    "categories": [
        24748,
        24169
    ],
    "categories_by_source_id": [
        "320999",
        "310112"
    ],
    "authors": [
        {
            "name": "Virginia Scarlett",
            "id": 14526911
        },
        {
            "name": "Ana Van Gulick",
            "id": 9314359
        }
    ],
    "defined_type": "dataset",
    "group_id": 11380
}
